version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      npm-all:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      pip-backend:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/jobs/graph-gen"
    schedule:
      interval: "weekly"
    groups:
      pip-graph-gen:
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
    groups:
      terraform-all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-all:
        patterns:
          - "*"
